# 
control_dt: 0.02

# Total simulation time
simulation_duration: 600000000.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4


policy_path: "/home/zju/Wheel_Legged_Gym-main/logs/go2_handstand/exported/policies/policy_dwaq.onnx"
xml_path: "/home/zju/Wheel_Legged_Gym-main/resources/robots/go2/go2/scene_terrain.xml"

kps: [25,25,25, 25, 25, 25, 25, 25, 25, 25, 25, 25, ]
kds: [0.5,0.5,0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,]


default_angles: [
                  0.0, 0.8, -1.5,  
                  0.0, 0.8, -1.5, 
                  0.0, 0.8, -1.5,  
                  0.0, 0.8, -1.5, ]

torque_limits: [200., 200., 320.,   
                200., 200., 320.,   
                200., 200., 320.,  
                200., 200., 320.,  ]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
cmd_scale: [2, 2, 0.25]
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_init: [0, 0, 0]


action_scale: 0.25

num_actions: 12
num_obs: 46