# 
control_dt: 0.02

# Total simulation time
simulation_duration: 600000000.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4


policy_path: "/home/zju/Wheel_Legged_Gym-main/logs/M20/exported/policies/policy_dwaq.onnx"
xml_path: "/home/zju/Wheel_Legged_Gym-main/deploy/deploy_mujoco/M20/mjcf/scene.xml"

joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

kps: [80, 80, 80, 0, 80, 80, 80, 0, 80, 80, 80, 0, 80, 80, 80, 0]
kds: [2, 2, 2, 0.6, 2, 2, 2, 0.6, 2, 2, 2, 0.6, 2, 2, 2, 0.6]


default_angles: [
                  0.0, -0.6, 1.0, 0.0, 
                  0.0, -0.6, 1.0, 0.0, 
                  0.0, 0.6, -1.0, 0.0, 
                  0.0, 0.6, -1.0, 0.0]

torque_limits: [200., 200., 320.,  20., 
                200., 200., 320.,  20., 
                200., 200., 320.,  20.,
                200., 200., 320.,  20.]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
cmd_scale: [2, 2, 0.25]
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_init: [0, 0, 0]

vel_scale: 5

action_scale: 0.25

num_actions: 16
num_obs: 57

wheel_sim_indices: [3, 7, 11, 15]


wheel_speed: 1